[package]
name = "qmk-xap-gui"
version = "0.0.0"
description = "QMK XAP client"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.65"

[build-dependencies]
tauri-build = { version = "1.1", features = [] }
ts-rs = { git = "https://github.com/Aleph-Alpha/ts-rs", branch = "main", features = [
    "serde-compat",
    "uuid-impl",
] }

[dependencies]
anyhow = "1.0"
binrw = "0.10"
bitflags = "1.3"
flate2 = "1.0"
crossbeam-channel = "0.5"
env_logger = "0.9"
hidapi = { version = "2.0.2", features = ["macos-shared-device"] }
log = "0.4"
parking_lot = "0.12.1"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
deser-hjson = "1"
serde_with = "2"
tauri = { version = "1.2", features = ["api-all", "system-tray"] }
thiserror = "1.0"
ts-rs = { git = "https://github.com/Aleph-Alpha/ts-rs", branch = "main", features = [
    "serde-compat",
    "uuid-impl",
] }
uuid = { version = "1.2.1", features = ["serde", "v4"] }
xap-specs = { path = "../xap-specs" }
reqwest = { version = "0.11", features = ["blocking", "json"] }
once_cell = "1.16"
percent-encoding = "2.1"
phf = { version = "0.11", features = ["macros"] }
dotenvy = "0.15.6"
rspotify = { version = "0.11.6", default-features = false, features = ["client-ureq", "ureq-rustls-tls", "cli"] }
image = "0.24.5"

[dev-dependencies]
similar-asserts = "1.4.2"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
opt-level = 'z'
lto = 'fat'
