// This file was generated by xap-specs, do not edit manually

pub mod error {
    #[derive(Debug, Clone, serde::Deserialize, serde::Serialize, specta::Type)]
    pub struct Error(pub String);

    impl From<anyhow::Error> for Error {
        fn from(err: anyhow::Error) -> Self {
            Self(err.to_string())
        }
    }
}

#[allow(dead_code)]
#[allow(unused_imports)]
pub mod xap {
    use std::sync::{Arc, Mutex};

    use std::result::Result;
    use tauri::State;
    use uuid::Uuid;

    use crate::rpc::spec::error::Error;
    use crate::xap::client::XapClient;
    use crate::xap::spec::types::*;
    use crate::xap::spec::xap::*;

    #[tauri::command]
    #[specta::specta]
    pub fn xap_version(
        id: Uuid,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<XapVersionResponse, Error> {
        state
            .lock()
            .unwrap()
            .query(id, XapVersionRequest(()))
            .map_err(Into::into)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn xap_capabilities(
        id: Uuid,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<XapCapabilitiesFlags, Error> {
        state
            .lock()
            .unwrap()
            .query(id, XapCapabilitiesRequest(()))
            .map_err(Into::into)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn xap_enabled_subsystem_capabilities(
        id: Uuid,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<XapEnabledSubsystemCapabilitiesFlags, Error> {
        state
            .lock()
            .unwrap()
            .query(id, XapEnabledSubsystemCapabilitiesRequest(()))
            .map_err(Into::into)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn xap_secure_status(
        id: Uuid,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<XapSecureStatusResponse, Error> {
        state
            .lock()
            .unwrap()
            .query(id, XapSecureStatusRequest(()))
            .map_err(Into::into)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn xap_secure_unlock(
        id: Uuid,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<(), Error> {
        state
            .lock()
            .unwrap()
            .query(id, XapSecureUnlockRequest(()))
            .map_err(Into::into)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn xap_secure_lock(id: Uuid, state: State<'_, Arc<Mutex<XapClient>>>) -> Result<(), Error> {
        state
            .lock()
            .unwrap()
            .query(id, XapSecureLockRequest(()))
            .map_err(Into::into)
    }
}

#[allow(dead_code)]
#[allow(unused_imports)]
pub mod qmk {
    use std::sync::{Arc, Mutex};

    use std::result::Result;
    use tauri::State;
    use uuid::Uuid;

    use crate::rpc::spec::error::Error;
    use crate::xap::client::XapClient;
    use crate::xap::spec::qmk::*;
    use crate::xap::spec::types::*;

    #[tauri::command]
    #[specta::specta]
    pub fn qmk_version(
        id: Uuid,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<QmkVersionResponse, Error> {
        state
            .lock()
            .unwrap()
            .query(id, QmkVersionRequest(()))
            .map_err(Into::into)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn qmk_capabilities(
        id: Uuid,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<QmkCapabilitiesFlags, Error> {
        state
            .lock()
            .unwrap()
            .query(id, QmkCapabilitiesRequest(()))
            .map_err(Into::into)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn qmk_board_identifiers(
        id: Uuid,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<QmkBoardIdentifiersResponse, Error> {
        state
            .lock()
            .unwrap()
            .query(id, QmkBoardIdentifiersRequest(()))
            .map_err(Into::into)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn qmk_board_manufacturer(
        id: Uuid,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<QmkBoardManufacturerResponse, Error> {
        state
            .lock()
            .unwrap()
            .query(id, QmkBoardManufacturerRequest(()))
            .map_err(Into::into)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn qmk_product_name(
        id: Uuid,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<QmkProductNameResponse, Error> {
        state
            .lock()
            .unwrap()
            .query(id, QmkProductNameRequest(()))
            .map_err(Into::into)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn qmk_config_blob_length(
        id: Uuid,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<QmkConfigBlobLengthResponse, Error> {
        state
            .lock()
            .unwrap()
            .query(id, QmkConfigBlobLengthRequest(()))
            .map_err(Into::into)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn qmk_config_blob_chunk(
        id: Uuid,
        arg: u16,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<QmkConfigBlobChunkResponse, Error> {
        state
            .lock()
            .unwrap()
            .query(id, QmkConfigBlobChunkRequest(arg))
            .map_err(Into::into)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn qmk_jump_to_bootloader(
        id: Uuid,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<QmkJumpToBootloaderResponse, Error> {
        state
            .lock()
            .unwrap()
            .query(id, QmkJumpToBootloaderRequest(()))
            .map_err(Into::into)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn qmk_hardware_identifier(
        id: Uuid,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<QmkHardwareIdentifierResponse, Error> {
        state
            .lock()
            .unwrap()
            .query(id, QmkHardwareIdentifierRequest(()))
            .map_err(Into::into)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn qmk_reinitialize_eeprom(
        id: Uuid,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<QmkReinitializeEepromResponse, Error> {
        state
            .lock()
            .unwrap()
            .query(id, QmkReinitializeEepromRequest(()))
            .map_err(Into::into)
    }
}

#[allow(dead_code)]
#[allow(unused_imports)]
pub mod keyboard {
    use std::sync::{Arc, Mutex};

    use std::result::Result;
    use tauri::State;
    use uuid::Uuid;

    use crate::rpc::spec::error::Error;
    use crate::xap::client::XapClient;
    use crate::xap::spec::keyboard::*;
    use crate::xap::spec::types::*;
}

#[allow(dead_code)]
#[allow(unused_imports)]
pub mod user {
    use std::sync::{Arc, Mutex};

    use std::result::Result;
    use tauri::State;
    use uuid::Uuid;

    use crate::rpc::spec::error::Error;
    use crate::xap::client::XapClient;
    use crate::xap::spec::types::*;
    use crate::xap::spec::user::*;

    #[tauri::command]
    #[specta::specta]
    pub fn user_capabilities(
        id: Uuid,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<UserCapabilitiesFlags, Error> {
        state
            .lock()
            .unwrap()
            .query(id, UserCapabilitiesRequest(()))
            .map_err(Into::into)
    }

    #[allow(dead_code)]
    #[allow(unused_imports)]
    pub mod quantum_painter {
        use std::sync::{Arc, Mutex};

        use std::result::Result;
        use tauri::State;
        use uuid::Uuid;

        use crate::rpc::spec::error::Error;
        use crate::xap::client::XapClient;
        use crate::xap::spec::types::*;
        use crate::xap::spec::user::quantum_painter::*;

        #[tauri::command]
        #[specta::specta]
        pub fn quantum_painterclear(
            id: Uuid,
            arg: QuantumPainterclearArg,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, QuantumPainterclearRequest(arg))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn quantum_paintersetpixel(
            id: Uuid,
            arg: QuantumPaintersetpixelArg,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, QuantumPaintersetpixelRequest(arg))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn quantum_painterline(
            id: Uuid,
            arg: QuantumPainterlineArg,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, QuantumPainterlineRequest(arg))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn quantum_painterrect(
            id: Uuid,
            arg: QuantumPainterrectArg,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, QuantumPainterrectRequest(arg))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn quantum_paintercircle(
            id: Uuid,
            arg: QuantumPaintercircleArg,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, QuantumPaintercircleRequest(arg))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn quantum_painterellipse(
            id: Uuid,
            arg: QuantumPainterellipseArg,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, QuantumPainterellipseRequest(arg))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn quantum_painterdrawimage(
            id: Uuid,
            arg: QuantumPainterdrawimageArg,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, QuantumPainterdrawimageRequest(arg))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn quantum_painterdrawimage_recolor(
            id: Uuid,
            arg: QuantumPainterdrawimageRecolorArg,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, QuantumPainterdrawimageRecolorRequest(arg))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn quantum_painteranimate(
            id: Uuid,
            arg: QuantumPainteranimateArg,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, QuantumPainteranimateRequest(arg))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn quantum_painteranimate_recolor(
            id: Uuid,
            arg: QuantumPainteranimateRecolorArg,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, QuantumPainteranimateRecolorRequest(arg))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn quantum_painterdrawtext(
            id: Uuid,
            arg: QuantumPainterdrawtextArg,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, QuantumPainterdrawtextRequest(arg))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn quantum_painterdrawtext_recolor(
            id: Uuid,
            arg: QuantumPainterdrawtextRecolorArg,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, QuantumPainterdrawtextRecolorRequest(arg))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn quantum_painterget_geometry(
            id: Uuid,
            arg: QuantumPaintergetGeometryArg,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, QuantumPaintergetGeometryRequest(arg))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn quantum_painterflush(
            id: Uuid,
            arg: QuantumPainterflushArg,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, QuantumPainterflushRequest(arg))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn quantum_painterviewport(
            id: Uuid,
            arg: QuantumPainterviewportArg,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, QuantumPainterviewportRequest(arg))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn quantum_painterpixdata(
            id: Uuid,
            arg: QuantumPainterpixdataArg,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, QuantumPainterpixdataRequest(arg))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn quantum_paintertextwidth(
            id: Uuid,
            arg: QuantumPaintertextwidthArg,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, QuantumPaintertextwidthRequest(arg))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn quantum_painterscrolling_text(
            id: Uuid,
            arg: QuantumPainterscrollingTextArg,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, QuantumPainterscrollingTextRequest(arg))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn quantum_painterscrolling_text_stop(
            id: Uuid,
            arg: QuantumPainterscrollingTextStopArg,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, QuantumPainterscrollingTextStopRequest(arg))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn quantum_painterscrolling_text_extend(
            id: Uuid,
            arg: QuantumPainterscrollingTextExtendArg,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, QuantumPainterscrollingTextExtendRequest(arg))
                .map_err(Into::into)
        }
    }

    #[allow(dead_code)]
    #[allow(unused_imports)]
    pub mod tasks {
        use std::sync::{Arc, Mutex};

        use std::result::Result;
        use tauri::State;
        use uuid::Uuid;

        use crate::rpc::spec::error::Error;
        use crate::xap::client::XapClient;
        use crate::xap::spec::types::*;
        use crate::xap::spec::user::tasks::*;

        #[tauri::command]
        #[specta::specta]
        pub fn taskspush_computer_stats(
            id: Uuid,
            arg: TaskspushComputerStatsArg,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, TaskspushComputerStatsRequest(arg))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn tasksset_github_notifications_count(
            id: Uuid,
            arg: TaskssetGithubNotificationsCountArg,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, TaskssetGithubNotificationsCountRequest(arg))
                .map_err(Into::into)
        }
    }
}

#[allow(dead_code)]
#[allow(unused_imports)]
pub mod keymap {
    use std::sync::{Arc, Mutex};

    use std::result::Result;
    use tauri::State;
    use uuid::Uuid;

    use crate::rpc::spec::error::Error;
    use crate::xap::client::XapClient;
    use crate::xap::spec::keymap::*;
    use crate::xap::spec::types::*;

    #[tauri::command]
    #[specta::specta]
    pub fn keymap_capabilities(
        id: Uuid,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<KeymapCapabilitiesFlags, Error> {
        state
            .lock()
            .unwrap()
            .query(id, KeymapCapabilitiesRequest(()))
            .map_err(Into::into)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn keymap_get_layer_count(
        id: Uuid,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<KeymapGetLayerCountResponse, Error> {
        state
            .lock()
            .unwrap()
            .query(id, KeymapGetLayerCountRequest(()))
            .map_err(Into::into)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn keymap_get_keycode(
        id: Uuid,
        arg: KeymapGetKeycodeArg,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<KeymapGetKeycodeResponse, Error> {
        state
            .lock()
            .unwrap()
            .query(id, KeymapGetKeycodeRequest(arg))
            .map_err(Into::into)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn keymap_get_encoder_keycode(
        id: Uuid,
        arg: KeymapGetEncoderKeycodeArg,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<KeymapGetEncoderKeycodeResponse, Error> {
        state
            .lock()
            .unwrap()
            .query(id, KeymapGetEncoderKeycodeRequest(arg))
            .map_err(Into::into)
    }
}

#[allow(dead_code)]
#[allow(unused_imports)]
pub mod remapping {
    use std::sync::{Arc, Mutex};

    use std::result::Result;
    use tauri::State;
    use uuid::Uuid;

    use crate::rpc::spec::error::Error;
    use crate::xap::client::XapClient;
    use crate::xap::spec::remapping::*;
    use crate::xap::spec::types::*;

    #[tauri::command]
    #[specta::specta]
    pub fn remapping_capabilities(
        id: Uuid,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<RemappingCapabilitiesFlags, Error> {
        state
            .lock()
            .unwrap()
            .query(id, RemappingCapabilitiesRequest(()))
            .map_err(Into::into)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn remapping_get_layer_count(
        id: Uuid,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<RemappingGetLayerCountResponse, Error> {
        state
            .lock()
            .unwrap()
            .query(id, RemappingGetLayerCountRequest(()))
            .map_err(Into::into)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn remapping_set_keycode(
        id: Uuid,
        arg: RemappingSetKeycodeArg,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<(), Error> {
        state
            .lock()
            .unwrap()
            .query(id, RemappingSetKeycodeRequest(arg))
            .map_err(Into::into)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn remapping_set_encoder_keycode(
        id: Uuid,
        arg: RemappingSetEncoderKeycodeArg,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<(), Error> {
        state
            .lock()
            .unwrap()
            .query(id, RemappingSetEncoderKeycodeRequest(arg))
            .map_err(Into::into)
    }
}

#[allow(dead_code)]
#[allow(unused_imports)]
pub mod lighting {
    use std::sync::{Arc, Mutex};

    use std::result::Result;
    use tauri::State;
    use uuid::Uuid;

    use crate::rpc::spec::error::Error;
    use crate::xap::client::XapClient;
    use crate::xap::spec::lighting::*;
    use crate::xap::spec::types::*;

    #[tauri::command]
    #[specta::specta]
    pub fn lighting_capabilities(
        id: Uuid,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<LightingCapabilitiesFlags, Error> {
        state
            .lock()
            .unwrap()
            .query(id, LightingCapabilitiesRequest(()))
            .map_err(Into::into)
    }

    #[allow(dead_code)]
    #[allow(unused_imports)]
    pub mod backlight {
        use std::sync::{Arc, Mutex};

        use std::result::Result;
        use tauri::State;
        use uuid::Uuid;

        use crate::rpc::spec::error::Error;
        use crate::xap::client::XapClient;
        use crate::xap::spec::lighting::backlight::*;
        use crate::xap::spec::types::*;

        #[tauri::command]
        #[specta::specta]
        pub fn backlight_capabilities(
            id: Uuid,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<BacklightCapabilitiesFlags, Error> {
            state
                .lock()
                .unwrap()
                .query(id, BacklightCapabilitiesRequest(()))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn backlight_get_enabled_effects(
            id: Uuid,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<BacklightGetEnabledEffectsResponse, Error> {
            state
                .lock()
                .unwrap()
                .query(id, BacklightGetEnabledEffectsRequest(()))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn backlight_get_config(
            id: Uuid,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<BacklightConfig, Error> {
            state
                .lock()
                .unwrap()
                .query(id, BacklightGetConfigRequest(()))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn backlight_set_config(
            id: Uuid,
            arg: BacklightConfig,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, BacklightSetConfigRequest(arg))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn backlight_save_config(
            id: Uuid,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, BacklightSaveConfigRequest(()))
                .map_err(Into::into)
        }
    }

    #[allow(dead_code)]
    #[allow(unused_imports)]
    pub mod rgblight {
        use std::sync::{Arc, Mutex};

        use std::result::Result;
        use tauri::State;
        use uuid::Uuid;

        use crate::rpc::spec::error::Error;
        use crate::xap::client::XapClient;
        use crate::xap::spec::lighting::rgblight::*;
        use crate::xap::spec::types::*;

        #[tauri::command]
        #[specta::specta]
        pub fn rgblight_capabilities(
            id: Uuid,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<RgblightCapabilitiesFlags, Error> {
            state
                .lock()
                .unwrap()
                .query(id, RgblightCapabilitiesRequest(()))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn rgblight_get_enabled_effects(
            id: Uuid,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<RgblightGetEnabledEffectsResponse, Error> {
            state
                .lock()
                .unwrap()
                .query(id, RgblightGetEnabledEffectsRequest(()))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn rgblight_get_config(
            id: Uuid,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<RgbLightConfig, Error> {
            state
                .lock()
                .unwrap()
                .query(id, RgblightGetConfigRequest(()))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn rgblight_set_config(
            id: Uuid,
            arg: RgbLightConfig,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, RgblightSetConfigRequest(arg))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn rgblight_save_config(
            id: Uuid,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, RgblightSaveConfigRequest(()))
                .map_err(Into::into)
        }
    }

    #[allow(dead_code)]
    #[allow(unused_imports)]
    pub mod rgbmatrix {
        use std::sync::{Arc, Mutex};

        use std::result::Result;
        use tauri::State;
        use uuid::Uuid;

        use crate::rpc::spec::error::Error;
        use crate::xap::client::XapClient;
        use crate::xap::spec::lighting::rgbmatrix::*;
        use crate::xap::spec::types::*;

        #[tauri::command]
        #[specta::specta]
        pub fn rgbmatrix_capabilities(
            id: Uuid,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<RgbmatrixCapabilitiesFlags, Error> {
            state
                .lock()
                .unwrap()
                .query(id, RgbmatrixCapabilitiesRequest(()))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn rgbmatrix_get_enabled_effects(
            id: Uuid,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<RgbmatrixGetEnabledEffectsResponse, Error> {
            state
                .lock()
                .unwrap()
                .query(id, RgbmatrixGetEnabledEffectsRequest(()))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn rgbmatrix_get_config(
            id: Uuid,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<RgbMatrixConfig, Error> {
            state
                .lock()
                .unwrap()
                .query(id, RgbmatrixGetConfigRequest(()))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn rgbmatrix_set_config(
            id: Uuid,
            arg: RgbMatrixConfig,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, RgbmatrixSetConfigRequest(arg))
                .map_err(Into::into)
        }

        #[tauri::command]
        #[specta::specta]
        pub fn rgbmatrix_save_config(
            id: Uuid,
            state: State<'_, Arc<Mutex<XapClient>>>,
        ) -> Result<(), Error> {
            state
                .lock()
                .unwrap()
                .query(id, RgbmatrixSaveConfigRequest(()))
                .map_err(Into::into)
        }
    }
}

#[allow(dead_code)]
#[allow(unused_imports)]
pub mod audio {
    use std::sync::{Arc, Mutex};

    use std::result::Result;
    use tauri::State;
    use uuid::Uuid;

    use crate::rpc::spec::error::Error;
    use crate::xap::client::XapClient;
    use crate::xap::spec::audio::*;
    use crate::xap::spec::types::*;

    #[tauri::command]
    #[specta::specta]
    pub fn audio_capabilities(
        id: Uuid,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<AudioCapabilitiesFlags, Error> {
        state
            .lock()
            .unwrap()
            .query(id, AudioCapabilitiesRequest(()))
            .map_err(Into::into)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn audio_get_config(
        id: Uuid,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<AudioConfig, Error> {
        state
            .lock()
            .unwrap()
            .query(id, AudioGetConfigRequest(()))
            .map_err(Into::into)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn audio_set_config(
        id: Uuid,
        arg: AudioConfig,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<(), Error> {
        state
            .lock()
            .unwrap()
            .query(id, AudioSetConfigRequest(arg))
            .map_err(Into::into)
    }

    #[tauri::command]
    #[specta::specta]
    pub fn audio_save_config(
        id: Uuid,
        state: State<'_, Arc<Mutex<XapClient>>>,
    ) -> Result<(), Error> {
        state
            .lock()
            .unwrap()
            .query(id, AudioSaveConfigRequest(()))
            .map_err(Into::into)
    }
}

#[macro_export]
macro_rules! generate_specta_builder {
                (commands: [$($command:ident),*], events: [$($event:ident),*]) => {{
                    let specta_builder = tauri_specta::Builder::new()
                        .commands(tauri_specta::collect_commands![
                            crate::rpc::spec::xap::xap_version,
                            crate::rpc::spec::xap::xap_capabilities,
                            crate::rpc::spec::xap::xap_enabled_subsystem_capabilities,
                            crate::rpc::spec::xap::xap_secure_status,
                            crate::rpc::spec::xap::xap_secure_unlock,
                            crate::rpc::spec::xap::xap_secure_lock,
                            crate::rpc::spec::qmk::qmk_version,
                            crate::rpc::spec::qmk::qmk_capabilities,
                            crate::rpc::spec::qmk::qmk_board_identifiers,
                            crate::rpc::spec::qmk::qmk_board_manufacturer,
                            crate::rpc::spec::qmk::qmk_product_name,
                            crate::rpc::spec::qmk::qmk_config_blob_length,
                            crate::rpc::spec::qmk::qmk_config_blob_chunk,
                            crate::rpc::spec::qmk::qmk_jump_to_bootloader,
                            crate::rpc::spec::qmk::qmk_hardware_identifier,
                            crate::rpc::spec::qmk::qmk_reinitialize_eeprom,
                            crate::rpc::spec::user::user_capabilities,
                            crate::rpc::spec::user::quantum_painter::quantum_painterclear,
                            crate::rpc::spec::user::quantum_painter::quantum_paintersetpixel,
                            crate::rpc::spec::user::quantum_painter::quantum_painterline,
                            crate::rpc::spec::user::quantum_painter::quantum_painterrect,
                            crate::rpc::spec::user::quantum_painter::quantum_paintercircle,
                            crate::rpc::spec::user::quantum_painter::quantum_painterellipse,
                            crate::rpc::spec::user::quantum_painter::quantum_painterdrawimage,
                            crate::rpc::spec::user::quantum_painter::quantum_painterdrawimage_recolor,
                            crate::rpc::spec::user::quantum_painter::quantum_painteranimate,
                            crate::rpc::spec::user::quantum_painter::quantum_painteranimate_recolor,
                            crate::rpc::spec::user::quantum_painter::quantum_painterdrawtext,
                            crate::rpc::spec::user::quantum_painter::quantum_painterdrawtext_recolor,
                            crate::rpc::spec::user::quantum_painter::quantum_painterget_geometry,
                            crate::rpc::spec::user::quantum_painter::quantum_painterflush,
                            crate::rpc::spec::user::quantum_painter::quantum_painterviewport,
                            crate::rpc::spec::user::quantum_painter::quantum_painterpixdata,
                            crate::rpc::spec::user::quantum_painter::quantum_paintertextwidth,
                            crate::rpc::spec::user::quantum_painter::quantum_painterscrolling_text,
                            crate::rpc::spec::user::quantum_painter::quantum_painterscrolling_text_stop,
                            crate::rpc::spec::user::quantum_painter::quantum_painterscrolling_text_extend,
                            crate::rpc::spec::user::tasks::taskspush_computer_stats,
                            crate::rpc::spec::user::tasks::tasksset_github_notifications_count,
                            crate::rpc::spec::keymap::keymap_capabilities,
                            crate::rpc::spec::keymap::keymap_get_layer_count,
                            crate::rpc::spec::keymap::keymap_get_keycode,
                            crate::rpc::spec::keymap::keymap_get_encoder_keycode,
                            crate::rpc::spec::remapping::remapping_capabilities,
                            crate::rpc::spec::remapping::remapping_get_layer_count,
                            crate::rpc::spec::remapping::remapping_set_keycode,
                            crate::rpc::spec::remapping::remapping_set_encoder_keycode,
                            crate::rpc::spec::lighting::lighting_capabilities,
                            crate::rpc::spec::lighting::backlight::backlight_capabilities,
                            crate::rpc::spec::lighting::backlight::backlight_get_enabled_effects,
                            crate::rpc::spec::lighting::backlight::backlight_get_config,
                            crate::rpc::spec::lighting::backlight::backlight_set_config,
                            crate::rpc::spec::lighting::backlight::backlight_save_config,
                            crate::rpc::spec::lighting::rgblight::rgblight_capabilities,
                            crate::rpc::spec::lighting::rgblight::rgblight_get_enabled_effects,
                            crate::rpc::spec::lighting::rgblight::rgblight_get_config,
                            crate::rpc::spec::lighting::rgblight::rgblight_set_config,
                            crate::rpc::spec::lighting::rgblight::rgblight_save_config,
                            crate::rpc::spec::lighting::rgbmatrix::rgbmatrix_capabilities,
                            crate::rpc::spec::lighting::rgbmatrix::rgbmatrix_get_enabled_effects,
                            crate::rpc::spec::lighting::rgbmatrix::rgbmatrix_get_config,
                            crate::rpc::spec::lighting::rgbmatrix::rgbmatrix_set_config,
                            crate::rpc::spec::lighting::rgbmatrix::rgbmatrix_save_config,
                            crate::rpc::spec::audio::audio_capabilities,
                            crate::rpc::spec::audio::audio_get_config,
                            crate::rpc::spec::audio::audio_set_config,
                            crate::rpc::spec::audio::audio_save_config,
                            $($command),*
                        ]).events(tauri_specta::collect_events![$($event),*]);

                    specta_builder
                }};
            }
