// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PainterKeycode { screen_id: number, x: number, y: number, font: number, layer: number, row: number, col: number, }