// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HSVColor } from "./HSVColor";

export interface PainterLine { dev: number, x0: number, y0: number, x1: number, y1: number, color: HSVColor, }