// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HSVColor } from "./HSVColor";

export interface PainterImageRecolor { dev: number, x: number, y: number, img: number, fg_color: HSVColor, bg_color: HSVColor, }