// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HSVColor } from "./HSVColor";

export interface PainterRect { dev: number, left: number, top: number, right: number, bottom: number, color: HSVColor, filled: number, }