// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HSVColor } from "./HSVColor";

export interface PainterCircle { screen_id: number, x: number, y: number, radius: number, color: HSVColor, filled: number, }