// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PainterScrollingText { screen_id: number, x: number, y: number, font: number, n_chars: number, delay: number, text: Array<number>, null: number, }