// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PainterGeometry { width: number, height: number, rotation: number, offset_x: number, offset_y: number, }