// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HSVColor } from "./HSVColor";

export interface PainterTextRecolor { screen_id: number, x: number, y: number, font: number, fg_color: HSVColor, bg_color: HSVColor, text: Array<number>, }