// This file was generated by xap-specs, do not edit manually

#[allow(dead_code)]
#[allow(unused_imports)]
pub mod xap {
    use binrw::{BinRead, BinWrite};
    use bitflags::bitflags;
    use serde::{Deserialize, Serialize};
    use specta::Type;

    use crate::xap::spec::types::*;
    use xap_specs::request::XapRequest;
    use xap_specs::response::UTF8String;

    /// ======================================================================
    /// Version
    ///
    /// XAP protocol version query.
    ///
    /// * Returns the BCD-encoded version in the format of XX.YY.ZZZZ => `0xXXYYZZZZ`
    ///     * e.g. 3.2.115 will match `0x03020115`, or bytes {0x15,0x01,0x02,0x03}.
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct XapVersionRequest(pub ());

    impl From<()> for XapVersionRequest {
        fn from(req: ()) -> Self {
            Self(req)
        }
    }

    impl XapRequest for XapVersionRequest {
        type Response = XapVersionResponse;

        fn id() -> &'static [u8] {
            &[0x00, 0x00]
        }

        fn xap_version() -> u32 {
            0x00000001
        }
    }

    #[derive(BinRead, Default, Debug, Clone, Serialize, Type)]
    pub struct XapVersionResponse(pub u32);

    /// ======================================================================
    ///  capabilities
    ///
    /// XAP subsystem capabilities query. Each bit should be considered as a "usable" route within this subsystem.
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct XapCapabilitiesRequest(pub ());

    impl From<()> for XapCapabilitiesRequest {
        fn from(req: ()) -> Self {
            Self(req)
        }
    }

    impl XapRequest for XapCapabilitiesRequest {
        type Response = XapCapabilitiesFlags;

        fn id() -> &'static [u8] {
            &[0x00, 0x01]
        }

        fn xap_version() -> u32 {
            0x00000100
        }
    }

    #[derive(
        BinRead, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Clone, Copy, Serialize, Type,
    )]
    pub struct XapCapabilitiesFlags(u32);

    bitflags! {
                    impl XapCapabilitiesFlags: u32 {

    const Version = 1 << 0;
    const Capabilities = 1 << 1;
    const EnabledSubsystemCapabilities = 1 << 2;
    const SecureStatus = 1 << 3;
    const SecureUnlock = 1 << 4;
    const SecureLock = 1 << 5;
    }
    }

    /// ======================================================================
    /// Enabled subsystem capabilities
    ///
    /// XAP protocol subsystem query. Each bit should be considered as a "usable" subsystem. For example, checking `(value & (1 << XAP_ROUTE_QMK) != 0)` means the QMK subsystem is enabled and available for querying.
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct XapEnabledSubsystemCapabilitiesRequest(pub ());

    impl From<()> for XapEnabledSubsystemCapabilitiesRequest {
        fn from(req: ()) -> Self {
            Self(req)
        }
    }

    impl XapRequest for XapEnabledSubsystemCapabilitiesRequest {
        type Response = XapEnabledSubsystemCapabilitiesFlags;

        fn id() -> &'static [u8] {
            &[0x00, 0x02]
        }

        fn xap_version() -> u32 {
            0x00000100
        }
    }

    #[derive(
        BinRead, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Clone, Copy, Serialize, Type,
    )]
    pub struct XapEnabledSubsystemCapabilitiesFlags(u32);

    bitflags! {
                    impl XapEnabledSubsystemCapabilitiesFlags: u32 {

    const Xap = 1 << 0;
    const Qmk = 1 << 1;
    const Keyboard = 1 << 2;
    const User = 1 << 3;
    const Keymap = 1 << 4;
    const Remapping = 1 << 5;
    const Lighting = 1 << 6;
    const Audio = 1 << 7;
    }
    }

    /// ======================================================================
    /// Secure Status
    ///
    /// Query secure route status
    ///
    /// * 0 means secure routes are disabled
    /// * 1 means unlock sequence initiated but incomplete
    /// * 2 means secure routes are allowed
    /// * any other value should be interpreted as disabled
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct XapSecureStatusRequest(pub ());

    impl From<()> for XapSecureStatusRequest {
        fn from(req: ()) -> Self {
            Self(req)
        }
    }

    impl XapRequest for XapSecureStatusRequest {
        type Response = XapSecureStatusResponse;

        fn id() -> &'static [u8] {
            &[0x00, 0x03]
        }

        fn xap_version() -> u32 {
            0x00000100
        }
    }

    #[derive(BinRead, Default, Debug, Clone, Serialize, Type)]
    pub struct XapSecureStatusResponse(pub u8);

    /// ======================================================================
    /// Secure Unlock
    ///
    /// Initiate secure route unlock sequence
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct XapSecureUnlockRequest(pub ());

    impl From<()> for XapSecureUnlockRequest {
        fn from(req: ()) -> Self {
            Self(req)
        }
    }

    impl XapRequest for XapSecureUnlockRequest {
        type Response = ();

        fn id() -> &'static [u8] {
            &[0x00, 0x04]
        }

        fn xap_version() -> u32 {
            0x00000100
        }
    }

    /// ======================================================================
    /// Secure Lock
    ///
    /// Disable secure routes
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct XapSecureLockRequest(pub ());

    impl From<()> for XapSecureLockRequest {
        fn from(req: ()) -> Self {
            Self(req)
        }
    }

    impl XapRequest for XapSecureLockRequest {
        type Response = ();

        fn id() -> &'static [u8] {
            &[0x00, 0x05]
        }

        fn xap_version() -> u32 {
            0x00000100
        }
    }
}

#[allow(dead_code)]
#[allow(unused_imports)]
pub mod qmk {
    use binrw::{BinRead, BinWrite};
    use bitflags::bitflags;
    use serde::{Deserialize, Serialize};
    use specta::Type;

    use crate::xap::spec::types::*;
    use xap_specs::request::XapRequest;
    use xap_specs::response::UTF8String;

    /// ======================================================================
    /// Version
    ///
    /// QMK protocol version query.
    ///
    /// * Returns the BCD-encoded version in the format of XX.YY.ZZZZ => `0xXXYYZZZZ`
    ///     * e.g. 3.2.115 will match `0x03020115`, or bytes {0x15,0x01,0x02,0x03}.
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct QmkVersionRequest(pub ());

    impl From<()> for QmkVersionRequest {
        fn from(req: ()) -> Self {
            Self(req)
        }
    }

    impl XapRequest for QmkVersionRequest {
        type Response = QmkVersionResponse;

        fn id() -> &'static [u8] {
            &[0x01, 0x00]
        }

        fn xap_version() -> u32 {
            0x00000100
        }
    }

    #[derive(BinRead, Default, Debug, Clone, Serialize, Type)]
    pub struct QmkVersionResponse(pub u32);

    /// ======================================================================
    ///  capabilities
    ///
    /// QMK subsystem capabilities query. Each bit should be considered as a "usable" route within this subsystem.
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct QmkCapabilitiesRequest(pub ());

    impl From<()> for QmkCapabilitiesRequest {
        fn from(req: ()) -> Self {
            Self(req)
        }
    }

    impl XapRequest for QmkCapabilitiesRequest {
        type Response = QmkCapabilitiesFlags;

        fn id() -> &'static [u8] {
            &[0x01, 0x01]
        }

        fn xap_version() -> u32 {
            0x00000100
        }
    }

    #[derive(
        BinRead, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Clone, Copy, Serialize, Type,
    )]
    pub struct QmkCapabilitiesFlags(u32);

    bitflags! {
                    impl QmkCapabilitiesFlags: u32 {

    const Version = 1 << 0;
    const Capabilities = 1 << 1;
    const BoardIdentifiers = 1 << 2;
    const BoardManufacturer = 1 << 3;
    const ProductName = 1 << 4;
    const ConfigBlobLength = 1 << 5;
    const ConfigBlobChunk = 1 << 6;
    const JumpToBootloader = 1 << 7;
    const HardwareIdentifier = 1 << 8;
    const ReinitializeEeprom = 1 << 9;
    }
    }

    /// ======================================================================
    /// Board identifiers
    ///
    /// Retrieves the set of identifying information for the board.
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct QmkBoardIdentifiersRequest(pub ());

    impl From<()> for QmkBoardIdentifiersRequest {
        fn from(req: ()) -> Self {
            Self(req)
        }
    }

    impl XapRequest for QmkBoardIdentifiersRequest {
        type Response = QmkBoardIdentifiersResponse;

        fn id() -> &'static [u8] {
            &[0x01, 0x02]
        }

        fn xap_version() -> u32 {
            0x00000100
        }
    }

    #[derive(BinRead, Default, Debug, Clone, Serialize, Type)]
    pub struct QmkBoardIdentifiersResponse {
        pub vendor_id: u16,
        pub product_id: u16,
        pub product_version: u16,
        pub qmk_unique_identifier: u32,
    }

    /// ======================================================================
    /// Board Manufacturer
    ///
    /// Retrieves the name of the manufacturer
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct QmkBoardManufacturerRequest(pub ());

    impl From<()> for QmkBoardManufacturerRequest {
        fn from(req: ()) -> Self {
            Self(req)
        }
    }

    impl XapRequest for QmkBoardManufacturerRequest {
        type Response = QmkBoardManufacturerResponse;

        fn id() -> &'static [u8] {
            &[0x01, 0x03]
        }

        fn xap_version() -> u32 {
            0x00000100
        }
    }

    #[derive(BinRead, Default, Debug, Clone, Serialize, Type)]
    pub struct QmkBoardManufacturerResponse(pub UTF8String);

    /// ======================================================================
    /// Product Name
    ///
    /// Retrieves the product name
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct QmkProductNameRequest(pub ());

    impl From<()> for QmkProductNameRequest {
        fn from(req: ()) -> Self {
            Self(req)
        }
    }

    impl XapRequest for QmkProductNameRequest {
        type Response = QmkProductNameResponse;

        fn id() -> &'static [u8] {
            &[0x01, 0x04]
        }

        fn xap_version() -> u32 {
            0x00000100
        }
    }

    #[derive(BinRead, Default, Debug, Clone, Serialize, Type)]
    pub struct QmkProductNameResponse(pub UTF8String);

    /// ======================================================================
    /// Config Blob Length
    ///
    /// Retrieves the length of the configuration data bundled within the firmware
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct QmkConfigBlobLengthRequest(pub ());

    impl From<()> for QmkConfigBlobLengthRequest {
        fn from(req: ()) -> Self {
            Self(req)
        }
    }

    impl XapRequest for QmkConfigBlobLengthRequest {
        type Response = QmkConfigBlobLengthResponse;

        fn id() -> &'static [u8] {
            &[0x01, 0x05]
        }

        fn xap_version() -> u32 {
            0x00000100
        }
    }

    #[derive(BinRead, Default, Debug, Clone, Serialize, Type)]
    pub struct QmkConfigBlobLengthResponse(pub u16);

    /// ======================================================================
    /// Config Blob Chunk
    ///
    /// Retrieves a chunk of the configuration data bundled within the firmware
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct QmkConfigBlobChunkRequest(pub u16);

    impl From<u16> for QmkConfigBlobChunkRequest {
        fn from(req: u16) -> Self {
            Self(req)
        }
    }

    impl XapRequest for QmkConfigBlobChunkRequest {
        type Response = QmkConfigBlobChunkResponse;

        fn id() -> &'static [u8] {
            &[0x01, 0x06]
        }

        fn xap_version() -> u32 {
            0x00000100
        }
    }

    #[derive(BinRead, Default, Debug, Clone, Serialize, Type)]
    pub struct QmkConfigBlobChunkResponse(pub [u8; 32]);

    /// ======================================================================
    /// Jump to bootloader
    ///
    /// Jump to bootloader
    ///
    /// May not be present - if QMK capabilities query returns “true”, then jump to bootloader is supported
    ///
    /// * 0 means secure routes are disabled, and should be considered as a failure
    /// * 1 means successful, board will jump to bootloader
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct QmkJumpToBootloaderRequest(pub ());

    impl From<()> for QmkJumpToBootloaderRequest {
        fn from(req: ()) -> Self {
            Self(req)
        }
    }

    impl XapRequest for QmkJumpToBootloaderRequest {
        type Response = QmkJumpToBootloaderResponse;

        fn id() -> &'static [u8] {
            &[0x01, 0x07]
        }

        fn xap_version() -> u32 {
            0x00000100
        }
    }

    #[derive(BinRead, Default, Debug, Clone, Serialize, Type)]
    pub struct QmkJumpToBootloaderResponse(pub u8);

    /// ======================================================================
    /// Hardware Identifier
    ///
    /// Retrieves a unique identifier for the board.
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct QmkHardwareIdentifierRequest(pub ());

    impl From<()> for QmkHardwareIdentifierRequest {
        fn from(req: ()) -> Self {
            Self(req)
        }
    }

    impl XapRequest for QmkHardwareIdentifierRequest {
        type Response = QmkHardwareIdentifierResponse;

        fn id() -> &'static [u8] {
            &[0x01, 0x08]
        }

        fn xap_version() -> u32 {
            0x00000100
        }
    }

    #[derive(BinRead, Default, Debug, Clone, Serialize, Type)]
    pub struct QmkHardwareIdentifierResponse(pub [u32; 4]);

    /// ======================================================================
    /// Reinitialize EEPROM
    ///
    /// Reinitializes the keyboard's EEPROM (persistent memory)
    ///
    /// May not be present - if QMK capabilities query returns “true”, then reinitialize is supported
    ///
    /// * 0 means secure routes are disabled, and should be considered as a failure
    /// * 1 means successful, board will reinitialize and then reboot
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct QmkReinitializeEepromRequest(pub ());

    impl From<()> for QmkReinitializeEepromRequest {
        fn from(req: ()) -> Self {
            Self(req)
        }
    }

    impl XapRequest for QmkReinitializeEepromRequest {
        type Response = QmkReinitializeEepromResponse;

        fn id() -> &'static [u8] {
            &[0x01, 0x09]
        }

        fn xap_version() -> u32 {
            0x00000100
        }
    }

    #[derive(BinRead, Default, Debug, Clone, Serialize, Type)]
    pub struct QmkReinitializeEepromResponse(pub u8);
}

#[allow(dead_code)]
#[allow(unused_imports)]
pub mod keyboard {
    use binrw::{BinRead, BinWrite};
    use bitflags::bitflags;
    use serde::{Deserialize, Serialize};
    use specta::Type;

    use crate::xap::spec::types::*;
    use xap_specs::request::XapRequest;
    use xap_specs::response::UTF8String;
}

#[allow(dead_code)]
#[allow(unused_imports)]
pub mod user {
    use binrw::{BinRead, BinWrite};
    use bitflags::bitflags;
    use serde::{Deserialize, Serialize};
    use specta::Type;

    use crate::xap::spec::types::*;
    use xap_specs::request::XapRequest;
    use xap_specs::response::UTF8String;

    /// ======================================================================
    ///  capabilities
    ///
    /// User subsystem capabilities query. Each bit should be considered as a "usable" route within this subsystem.
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct UserCapabilitiesRequest(pub ());

    impl From<()> for UserCapabilitiesRequest {
        fn from(req: ()) -> Self {
            Self(req)
        }
    }

    impl XapRequest for UserCapabilitiesRequest {
        type Response = UserCapabilitiesFlags;

        fn id() -> &'static [u8] {
            &[0x03, 0x01]
        }

        fn xap_version() -> u32 {
            0x00000300
        }
    }

    #[derive(
        BinRead, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Clone, Copy, Serialize, Type,
    )]
    pub struct UserCapabilitiesFlags(u32);

    bitflags! {
                    impl UserCapabilitiesFlags: u32 {

    const Capabilities = 1 << 1;
    const QuantumPainter = 1 << 2;
    }
    }

    #[allow(dead_code)]
    #[allow(unused_imports)]
    pub mod quantum_painter {
        use binrw::{BinRead, BinWrite};
        use bitflags::bitflags;
        use serde::{Deserialize, Serialize};
        use specta::Type;

        use crate::xap::spec::types::*;
        use xap_specs::request::XapRequest;
        use xap_specs::response::UTF8String;

        /// ======================================================================
        /// clear
        ///
        /// Expose `qp_clear`
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct QuantumPainterclearRequest(pub QuantumPainterclearArg);

        #[derive(BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
        pub struct QuantumPainterclearArg {
            pub device_name: [u8; 9],
            pub dev_terminator: u8,
        }

        impl From<QuantumPainterclearArg> for QuantumPainterclearRequest {
            fn from(req: QuantumPainterclearArg) -> Self {
                Self(req)
            }
        }

        impl XapRequest for QuantumPainterclearRequest {
            type Response = ();

            fn id() -> &'static [u8] {
                &[0x03, 0x02, 0x01]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        /// ======================================================================
        /// setpixel
        ///
        /// Expose `qp_setpixel`
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct QuantumPaintersetpixelRequest(pub QuantumPaintersetpixelArg);

        #[derive(BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
        pub struct QuantumPaintersetpixelArg {
            pub device_name: [u8; 9],
            pub dev_terminator: u8,
            pub x: u16,
            pub y: u16,
            pub hue: u8,
            pub sat: u8,
            pub val: u8,
        }

        impl From<QuantumPaintersetpixelArg> for QuantumPaintersetpixelRequest {
            fn from(req: QuantumPaintersetpixelArg) -> Self {
                Self(req)
            }
        }

        impl XapRequest for QuantumPaintersetpixelRequest {
            type Response = ();

            fn id() -> &'static [u8] {
                &[0x03, 0x02, 0x02]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        /// ======================================================================
        /// line
        ///
        /// Expose `qp_line`
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct QuantumPainterlineRequest(pub QuantumPainterlineArg);

        #[derive(BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
        pub struct QuantumPainterlineArg {
            pub device_name: [u8; 9],
            pub dev_terminator: u8,
            pub x_0: u16,
            pub y_0: u16,
            pub x_1: u16,
            pub y_1: u16,
            pub hue: u8,
            pub sat: u8,
            pub val: u8,
        }

        impl From<QuantumPainterlineArg> for QuantumPainterlineRequest {
            fn from(req: QuantumPainterlineArg) -> Self {
                Self(req)
            }
        }

        impl XapRequest for QuantumPainterlineRequest {
            type Response = ();

            fn id() -> &'static [u8] {
                &[0x03, 0x02, 0x03]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        /// ======================================================================
        /// rect
        ///
        /// Expose `qp_rect`
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct QuantumPainterrectRequest(pub QuantumPainterrectArg);

        #[derive(BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
        pub struct QuantumPainterrectArg {
            pub device_name: [u8; 9],
            pub dev_terminator: u8,
            pub left: u16,
            pub top: u16,
            pub right: u16,
            pub bottom: u16,
            pub hue: u8,
            pub sat: u8,
            pub val: u8,
            pub filled: u8,
        }

        impl From<QuantumPainterrectArg> for QuantumPainterrectRequest {
            fn from(req: QuantumPainterrectArg) -> Self {
                Self(req)
            }
        }

        impl XapRequest for QuantumPainterrectRequest {
            type Response = ();

            fn id() -> &'static [u8] {
                &[0x03, 0x02, 0x04]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        /// ======================================================================
        /// circle
        ///
        /// Expose `qp_circle`
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct QuantumPaintercircleRequest(pub QuantumPaintercircleArg);

        #[derive(BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
        pub struct QuantumPaintercircleArg {
            pub device_name: [u8; 9],
            pub dev_terminator: u8,
            pub x: u16,
            pub y: u16,
            pub radius: u16,
            pub hue: u8,
            pub sat: u8,
            pub val: u8,
            pub filled: u8,
        }

        impl From<QuantumPaintercircleArg> for QuantumPaintercircleRequest {
            fn from(req: QuantumPaintercircleArg) -> Self {
                Self(req)
            }
        }

        impl XapRequest for QuantumPaintercircleRequest {
            type Response = ();

            fn id() -> &'static [u8] {
                &[0x03, 0x02, 0x05]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        /// ======================================================================
        /// ellipse
        ///
        /// Expose `qp_ellipse`
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct QuantumPainterellipseRequest(pub QuantumPainterellipseArg);

        #[derive(BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
        pub struct QuantumPainterellipseArg {
            pub device_name: [u8; 9],
            pub dev_terminator: u8,
            pub x: u16,
            pub y: u16,
            pub sizex: u16,
            pub sizey: u16,
            pub hue: u8,
            pub sat: u8,
            pub val: u8,
            pub filled: u8,
        }

        impl From<QuantumPainterellipseArg> for QuantumPainterellipseRequest {
            fn from(req: QuantumPainterellipseArg) -> Self {
                Self(req)
            }
        }

        impl XapRequest for QuantumPainterellipseRequest {
            type Response = ();

            fn id() -> &'static [u8] {
                &[0x03, 0x02, 0x06]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        /// ======================================================================
        /// drawimage
        ///
        /// Expose `qp_drawimage`
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct QuantumPainterdrawimageRequest(pub QuantumPainterdrawimageArg);

        #[derive(BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
        pub struct QuantumPainterdrawimageArg {
            pub device_name: [u8; 9],
            pub dev_terminator: u8,
            pub x: u16,
            pub y: u16,
            pub image_name: [u8; 9],
            pub image_terminator: u8,
        }

        impl From<QuantumPainterdrawimageArg> for QuantumPainterdrawimageRequest {
            fn from(req: QuantumPainterdrawimageArg) -> Self {
                Self(req)
            }
        }

        impl XapRequest for QuantumPainterdrawimageRequest {
            type Response = ();

            fn id() -> &'static [u8] {
                &[0x03, 0x02, 0x07]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        /// ======================================================================
        /// drawimage_recolor
        ///
        /// Expose `qp_drawimage_recolor`
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct QuantumPainterdrawimageRecolorRequest(pub QuantumPainterdrawimageRecolorArg);

        #[derive(BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
        pub struct QuantumPainterdrawimageRecolorArg {
            pub device_name: [u8; 9],
            pub dev_terminator: u8,
            pub x: u16,
            pub y: u16,
            pub image_name: [u8; 9],
            pub image_terminator: u8,
            pub hue_fg: u8,
            pub sat_fg: u8,
            pub val_fg: u8,
            pub hue_bg: u8,
            pub sat_bg: u8,
            pub val_bg: u8,
        }

        impl From<QuantumPainterdrawimageRecolorArg> for QuantumPainterdrawimageRecolorRequest {
            fn from(req: QuantumPainterdrawimageRecolorArg) -> Self {
                Self(req)
            }
        }

        impl XapRequest for QuantumPainterdrawimageRecolorRequest {
            type Response = ();

            fn id() -> &'static [u8] {
                &[0x03, 0x02, 0x08]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        /// ======================================================================
        /// animate
        ///
        /// Expose `qp_animate`
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct QuantumPainteranimateRequest(pub QuantumPainteranimateArg);

        #[derive(BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
        pub struct QuantumPainteranimateArg {
            pub device_name: [u8; 9],
            pub dev_terminator: u8,
            pub x: u16,
            pub y: u16,
            pub image_name: [u8; 9],
            pub image_terminator: u8,
        }

        impl From<QuantumPainteranimateArg> for QuantumPainteranimateRequest {
            fn from(req: QuantumPainteranimateArg) -> Self {
                Self(req)
            }
        }

        impl XapRequest for QuantumPainteranimateRequest {
            type Response = ();

            fn id() -> &'static [u8] {
                &[0x03, 0x02, 0x09]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        /// ======================================================================
        /// animate_recolor
        ///
        /// Expose `qp_animate_recolor`
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct QuantumPainteranimateRecolorRequest(pub QuantumPainteranimateRecolorArg);

        #[derive(BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
        pub struct QuantumPainteranimateRecolorArg {
            pub device_name: [u8; 9],
            pub dev_terminator: u8,
            pub x: u16,
            pub y: u16,
            pub image_name: [u8; 9],
            pub image_terminator: u8,
            pub hue_fg: u8,
            pub sat_fg: u8,
            pub val_fg: u8,
            pub hue_bg: u8,
            pub sat_bg: u8,
            pub val_bg: u8,
        }

        impl From<QuantumPainteranimateRecolorArg> for QuantumPainteranimateRecolorRequest {
            fn from(req: QuantumPainteranimateRecolorArg) -> Self {
                Self(req)
            }
        }

        impl XapRequest for QuantumPainteranimateRecolorRequest {
            type Response = ();

            fn id() -> &'static [u8] {
                &[0x03, 0x02, 0x0a]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        /// ======================================================================
        /// drawtext
        ///
        /// Expose `qp_drawtext`
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct QuantumPainterdrawtextRequest(pub QuantumPainterdrawtextArg);

        #[derive(BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
        pub struct QuantumPainterdrawtextArg {
            pub device_name: [u8; 9],
            pub dev_terminator: u8,
            pub x: u16,
            pub y: u16,
            pub font_name: [u8; 9],
            pub font_terminator: u8,
            pub text: [u8; 32],
            pub text_terminator: u8,
        }

        impl From<QuantumPainterdrawtextArg> for QuantumPainterdrawtextRequest {
            fn from(req: QuantumPainterdrawtextArg) -> Self {
                Self(req)
            }
        }

        impl XapRequest for QuantumPainterdrawtextRequest {
            type Response = ();

            fn id() -> &'static [u8] {
                &[0x03, 0x02, 0x0b]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        /// ======================================================================
        /// drawtext_recolor
        ///
        /// Expose `qp_drawtext_recolor`
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct QuantumPainterdrawtextRecolorRequest(pub QuantumPainterdrawtextRecolorArg);

        #[derive(BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
        pub struct QuantumPainterdrawtextRecolorArg {
            pub device_name: [u8; 9],
            pub dev_terminator: u8,
            pub x: u16,
            pub y: u16,
            pub font_name: [u8; 9],
            pub font_terminator: u8,
            pub hue_fg: u8,
            pub sat_fg: u8,
            pub val_fg: u8,
            pub hue_bg: u8,
            pub sat_bg: u8,
            pub val_bg: u8,
            pub text: [u8; 27],
            pub null_terminator: u8,
        }

        impl From<QuantumPainterdrawtextRecolorArg> for QuantumPainterdrawtextRecolorRequest {
            fn from(req: QuantumPainterdrawtextRecolorArg) -> Self {
                Self(req)
            }
        }

        impl XapRequest for QuantumPainterdrawtextRecolorRequest {
            type Response = ();

            fn id() -> &'static [u8] {
                &[0x03, 0x02, 0x0c]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        /// ======================================================================
        /// get_geometry
        ///
        /// Expose `qp_get_geometry`
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct QuantumPaintergetGeometryRequest(pub QuantumPaintergetGeometryArg);

        #[derive(BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
        pub struct QuantumPaintergetGeometryArg {
            pub device_name: [u8; 9],
            pub dev_terminator: u8,
        }

        impl From<QuantumPaintergetGeometryArg> for QuantumPaintergetGeometryRequest {
            fn from(req: QuantumPaintergetGeometryArg) -> Self {
                Self(req)
            }
        }

        impl XapRequest for QuantumPaintergetGeometryRequest {
            type Response = ();

            fn id() -> &'static [u8] {
                &[0x03, 0x02, 0x0d]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        /// ======================================================================
        /// flush
        ///
        /// Expose `qp_flush`
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct QuantumPainterflushRequest(pub QuantumPainterflushArg);

        #[derive(BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
        pub struct QuantumPainterflushArg {
            pub device_name: [u8; 9],
            pub dev_terminator: u8,
        }

        impl From<QuantumPainterflushArg> for QuantumPainterflushRequest {
            fn from(req: QuantumPainterflushArg) -> Self {
                Self(req)
            }
        }

        impl XapRequest for QuantumPainterflushRequest {
            type Response = ();

            fn id() -> &'static [u8] {
                &[0x03, 0x02, 0x0e]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        /// ======================================================================
        /// viewport
        ///
        /// Expose `qp_viewport`
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct QuantumPainterviewportRequest(pub QuantumPainterviewportArg);

        #[derive(BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
        pub struct QuantumPainterviewportArg {
            pub device_name: [u8; 9],
            pub dev_terminator: u8,
            pub left: u16,
            pub top: u16,
            pub right: u16,
            pub bottom: u16,
        }

        impl From<QuantumPainterviewportArg> for QuantumPainterviewportRequest {
            fn from(req: QuantumPainterviewportArg) -> Self {
                Self(req)
            }
        }

        impl XapRequest for QuantumPainterviewportRequest {
            type Response = ();

            fn id() -> &'static [u8] {
                &[0x03, 0x02, 0x0f]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        /// ======================================================================
        /// pixdata
        ///
        /// Expose `qp_pixdata` to stream pixels over XAP
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct QuantumPainterpixdataRequest(pub QuantumPainterpixdataArg);

        #[derive(BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
        pub struct QuantumPainterpixdataArg {
            pub device_name: [u8; 9],
            pub dev_terminator: u8,
            pub pixels: [u8; 32],
        }

        impl From<QuantumPainterpixdataArg> for QuantumPainterpixdataRequest {
            fn from(req: QuantumPainterpixdataArg) -> Self {
                Self(req)
            }
        }

        impl XapRequest for QuantumPainterpixdataRequest {
            type Response = ();

            fn id() -> &'static [u8] {
                &[0x03, 0x02, 0x10]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        /// ======================================================================
        /// textwidth
        ///
        /// Expose `qp_textwidth`
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct QuantumPaintertextwidthRequest(pub QuantumPaintertextwidthArg);

        #[derive(BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
        pub struct QuantumPaintertextwidthArg {
            pub font_name: [u8; 9],
            pub font_terminator: u8,
            pub text: [u8; 32],
            pub null_terminator: u8,
        }

        impl From<QuantumPaintertextwidthArg> for QuantumPaintertextwidthRequest {
            fn from(req: QuantumPaintertextwidthArg) -> Self {
                Self(req)
            }
        }

        impl XapRequest for QuantumPaintertextwidthRequest {
            type Response = ();

            fn id() -> &'static [u8] {
                &[0x03, 0x02, 0x12]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        /// ======================================================================
        /// scrolling_text
        ///
        /// Expose `scrolling_text_start`
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct QuantumPainterscrollingTextRequest(pub QuantumPainterscrollingTextArg);

        #[derive(BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
        pub struct QuantumPainterscrollingTextArg {
            pub device_name: [u8; 9],
            pub dev_terminator: u8,
            pub x: u16,
            pub y: u16,
            pub font_name: [u8; 9],
            pub null_terminator_1: u8,
            pub n_chars: u8,
            pub delay: u16,
            pub text: [u8; 30],
            pub text_terminator: u8,
        }

        impl From<QuantumPainterscrollingTextArg> for QuantumPainterscrollingTextRequest {
            fn from(req: QuantumPainterscrollingTextArg) -> Self {
                Self(req)
            }
        }

        impl XapRequest for QuantumPainterscrollingTextRequest {
            type Response = ();

            fn id() -> &'static [u8] {
                &[0x03, 0x02, 0x13]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        /// ======================================================================
        /// scrolling_text_stop
        ///
        /// Expose `scrolling_text_stop`
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct QuantumPainterscrollingTextStopRequest(pub QuantumPainterscrollingTextStopArg);

        #[derive(BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
        pub struct QuantumPainterscrollingTextStopArg {
            pub token: u8,
        }

        impl From<QuantumPainterscrollingTextStopArg> for QuantumPainterscrollingTextStopRequest {
            fn from(req: QuantumPainterscrollingTextStopArg) -> Self {
                Self(req)
            }
        }

        impl XapRequest for QuantumPainterscrollingTextStopRequest {
            type Response = ();

            fn id() -> &'static [u8] {
                &[0x03, 0x02, 0x14]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        /// ======================================================================
        /// scrolling_text_extend
        ///
        /// Expose `scrolling_text_extend`
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct QuantumPainterscrollingTextExtendRequest(
            pub QuantumPainterscrollingTextExtendArg,
        );

        #[derive(BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
        pub struct QuantumPainterscrollingTextExtendArg {
            pub token: u8,
            pub text: [u8; 32],
            pub text_terminator: u8,
        }

        impl From<QuantumPainterscrollingTextExtendArg> for QuantumPainterscrollingTextExtendRequest {
            fn from(req: QuantumPainterscrollingTextExtendArg) -> Self {
                Self(req)
            }
        }

        impl XapRequest for QuantumPainterscrollingTextExtendRequest {
            type Response = ();

            fn id() -> &'static [u8] {
                &[0x03, 0x02, 0x15]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        /// ======================================================================
        /// push_computer_stats
        ///
        /// Expose `push_computer_stats`
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct QuantumPainterpushComputerStatsRequest(pub QuantumPainterpushComputerStatsArg);

        #[derive(BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
        pub struct QuantumPainterpushComputerStatsArg {
            pub cpu: u8,
            pub ram: u8,
        }

        impl From<QuantumPainterpushComputerStatsArg> for QuantumPainterpushComputerStatsRequest {
            fn from(req: QuantumPainterpushComputerStatsArg) -> Self {
                Self(req)
            }
        }

        impl XapRequest for QuantumPainterpushComputerStatsRequest {
            type Response = ();

            fn id() -> &'static [u8] {
                &[0x03, 0x02, 0x16]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }
    }
}

#[allow(dead_code)]
#[allow(unused_imports)]
pub mod keymap {
    use binrw::{BinRead, BinWrite};
    use bitflags::bitflags;
    use serde::{Deserialize, Serialize};
    use specta::Type;

    use crate::xap::spec::types::*;
    use xap_specs::request::XapRequest;
    use xap_specs::response::UTF8String;

    /// ======================================================================
    ///  capabilities
    ///
    /// Keymap subsystem capabilities query. Each bit should be considered as a "usable" route within this subsystem.
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct KeymapCapabilitiesRequest(pub ());

    impl From<()> for KeymapCapabilitiesRequest {
        fn from(req: ()) -> Self {
            Self(req)
        }
    }

    impl XapRequest for KeymapCapabilitiesRequest {
        type Response = KeymapCapabilitiesFlags;

        fn id() -> &'static [u8] {
            &[0x04, 0x01]
        }

        fn xap_version() -> u32 {
            0x00000200
        }
    }

    #[derive(
        BinRead, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Clone, Copy, Serialize, Type,
    )]
    pub struct KeymapCapabilitiesFlags(u32);

    bitflags! {
                    impl KeymapCapabilitiesFlags: u32 {

    const Capabilities = 1 << 1;
    const GetLayerCount = 1 << 2;
    const GetKeycode = 1 << 3;
    const GetEncoderKeycode = 1 << 4;
    }
    }

    /// ======================================================================
    /// Get Layer Count
    ///
    /// Query maximum number of layers that can be addressed within the keymap.
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct KeymapGetLayerCountRequest(pub ());

    impl From<()> for KeymapGetLayerCountRequest {
        fn from(req: ()) -> Self {
            Self(req)
        }
    }

    impl XapRequest for KeymapGetLayerCountRequest {
        type Response = KeymapGetLayerCountResponse;

        fn id() -> &'static [u8] {
            &[0x04, 0x02]
        }

        fn xap_version() -> u32 {
            0x00000200
        }
    }

    #[derive(BinRead, Default, Debug, Clone, Serialize, Type)]
    pub struct KeymapGetLayerCountResponse(pub u8);

    /// ======================================================================
    /// Get Keycode
    ///
    /// Query the Keycode at the requested location.
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct KeymapGetKeycodeRequest(pub KeymapGetKeycodeArg);

    #[derive(BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
    pub struct KeymapGetKeycodeArg {
        pub layer: u8,
        pub row: u8,
        pub column: u8,
    }

    impl From<KeymapGetKeycodeArg> for KeymapGetKeycodeRequest {
        fn from(req: KeymapGetKeycodeArg) -> Self {
            Self(req)
        }
    }

    impl XapRequest for KeymapGetKeycodeRequest {
        type Response = KeymapGetKeycodeResponse;

        fn id() -> &'static [u8] {
            &[0x04, 0x03]
        }

        fn xap_version() -> u32 {
            0x00000200
        }
    }

    #[derive(BinRead, Default, Debug, Clone, Serialize, Type)]
    pub struct KeymapGetKeycodeResponse(pub u16);

    /// ======================================================================
    /// Get Encoder Keycode
    ///
    /// Query the Keycode at the requested location.
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct KeymapGetEncoderKeycodeRequest(pub KeymapGetEncoderKeycodeArg);

    #[derive(BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
    pub struct KeymapGetEncoderKeycodeArg {
        pub layer: u8,
        pub encoder: u8,
        pub clockwise: u8,
    }

    impl From<KeymapGetEncoderKeycodeArg> for KeymapGetEncoderKeycodeRequest {
        fn from(req: KeymapGetEncoderKeycodeArg) -> Self {
            Self(req)
        }
    }

    impl XapRequest for KeymapGetEncoderKeycodeRequest {
        type Response = KeymapGetEncoderKeycodeResponse;

        fn id() -> &'static [u8] {
            &[0x04, 0x04]
        }

        fn xap_version() -> u32 {
            0x00000200
        }
    }

    #[derive(BinRead, Default, Debug, Clone, Serialize, Type)]
    pub struct KeymapGetEncoderKeycodeResponse(pub u16);
}

#[allow(dead_code)]
#[allow(unused_imports)]
pub mod remapping {
    use binrw::{BinRead, BinWrite};
    use bitflags::bitflags;
    use serde::{Deserialize, Serialize};
    use specta::Type;

    use crate::xap::spec::types::*;
    use xap_specs::request::XapRequest;
    use xap_specs::response::UTF8String;

    /// ======================================================================
    ///  capabilities
    ///
    /// Remapping subsystem capabilities query. Each bit should be considered as a "usable" route within this subsystem.
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct RemappingCapabilitiesRequest(pub ());

    impl From<()> for RemappingCapabilitiesRequest {
        fn from(req: ()) -> Self {
            Self(req)
        }
    }

    impl XapRequest for RemappingCapabilitiesRequest {
        type Response = RemappingCapabilitiesFlags;

        fn id() -> &'static [u8] {
            &[0x05, 0x01]
        }

        fn xap_version() -> u32 {
            0x00000200
        }
    }

    #[derive(
        BinRead, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Clone, Copy, Serialize, Type,
    )]
    pub struct RemappingCapabilitiesFlags(u32);

    bitflags! {
                    impl RemappingCapabilitiesFlags: u32 {

    const Capabilities = 1 << 1;
    const GetLayerCount = 1 << 2;
    const SetKeycode = 1 << 3;
    const SetEncoderKeycode = 1 << 4;
    }
    }

    /// ======================================================================
    /// Get Layer Count
    ///
    /// Query maximum number of layers that can be addressed within the keymap.
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct RemappingGetLayerCountRequest(pub ());

    impl From<()> for RemappingGetLayerCountRequest {
        fn from(req: ()) -> Self {
            Self(req)
        }
    }

    impl XapRequest for RemappingGetLayerCountRequest {
        type Response = RemappingGetLayerCountResponse;

        fn id() -> &'static [u8] {
            &[0x05, 0x02]
        }

        fn xap_version() -> u32 {
            0x00000200
        }
    }

    #[derive(BinRead, Default, Debug, Clone, Serialize, Type)]
    pub struct RemappingGetLayerCountResponse(pub u8);

    /// ======================================================================
    /// Set Keycode
    ///
    /// Modify the Keycode at the requested location.
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct RemappingSetKeycodeRequest(pub RemappingSetKeycodeArg);

    #[derive(BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
    pub struct RemappingSetKeycodeArg {
        pub layer: u8,
        pub row: u8,
        pub column: u8,
        pub keycode: u16,
    }

    impl From<RemappingSetKeycodeArg> for RemappingSetKeycodeRequest {
        fn from(req: RemappingSetKeycodeArg) -> Self {
            Self(req)
        }
    }

    impl XapRequest for RemappingSetKeycodeRequest {
        type Response = ();

        fn id() -> &'static [u8] {
            &[0x05, 0x03]
        }

        fn xap_version() -> u32 {
            0x00000200
        }
    }

    /// ======================================================================
    /// Set Encoder Keycode
    ///
    /// Modify the Keycode at the requested location.
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct RemappingSetEncoderKeycodeRequest(pub RemappingSetEncoderKeycodeArg);

    #[derive(BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
    pub struct RemappingSetEncoderKeycodeArg {
        pub layer: u8,
        pub encoder: u8,
        pub clockwise: u8,
        pub keycode: u16,
    }

    impl From<RemappingSetEncoderKeycodeArg> for RemappingSetEncoderKeycodeRequest {
        fn from(req: RemappingSetEncoderKeycodeArg) -> Self {
            Self(req)
        }
    }

    impl XapRequest for RemappingSetEncoderKeycodeRequest {
        type Response = ();

        fn id() -> &'static [u8] {
            &[0x05, 0x04]
        }

        fn xap_version() -> u32 {
            0x00000200
        }
    }
}

#[allow(dead_code)]
#[allow(unused_imports)]
pub mod lighting {
    use binrw::{BinRead, BinWrite};
    use bitflags::bitflags;
    use serde::{Deserialize, Serialize};
    use specta::Type;

    use crate::xap::spec::types::*;
    use xap_specs::request::XapRequest;
    use xap_specs::response::UTF8String;

    /// ======================================================================
    ///  capabilities
    ///
    /// Lighting subsystem capabilities query. Each bit should be considered as a "usable" route within this subsystem.
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct LightingCapabilitiesRequest(pub ());

    impl From<()> for LightingCapabilitiesRequest {
        fn from(req: ()) -> Self {
            Self(req)
        }
    }

    impl XapRequest for LightingCapabilitiesRequest {
        type Response = LightingCapabilitiesFlags;

        fn id() -> &'static [u8] {
            &[0x06, 0x01]
        }

        fn xap_version() -> u32 {
            0x00000200
        }
    }

    #[derive(
        BinRead, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Clone, Copy, Serialize, Type,
    )]
    pub struct LightingCapabilitiesFlags(u32);

    bitflags! {
                    impl LightingCapabilitiesFlags: u32 {

    const Capabilities = 1 << 1;
    const Backlight = 1 << 2;
    const Rgblight = 1 << 3;
    const Rgbmatrix = 1 << 4;
    }
    }

    #[allow(dead_code)]
    #[allow(unused_imports)]
    pub mod backlight {
        use binrw::{BinRead, BinWrite};
        use bitflags::bitflags;
        use serde::{Deserialize, Serialize};
        use specta::Type;

        use crate::xap::spec::types::*;
        use xap_specs::request::XapRequest;
        use xap_specs::response::UTF8String;

        /// ======================================================================
        ///  capabilities
        ///
        /// backlight subsystem capabilities query. Each bit should be considered as a "usable" route within this subsystem.
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct BacklightCapabilitiesRequest(pub ());

        impl From<()> for BacklightCapabilitiesRequest {
            fn from(req: ()) -> Self {
                Self(req)
            }
        }

        impl XapRequest for BacklightCapabilitiesRequest {
            type Response = BacklightCapabilitiesFlags;

            fn id() -> &'static [u8] {
                &[0x06, 0x02, 0x01]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        #[derive(
            BinRead, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Clone, Copy, Serialize, Type,
        )]
        pub struct BacklightCapabilitiesFlags(u32);

        bitflags! {
                        impl BacklightCapabilitiesFlags: u32 {

        const Capabilities = 1 << 1;
        const GetEnabledEffects = 1 << 2;
        const GetConfig = 1 << 3;
        const SetConfig = 1 << 4;
        const SaveConfig = 1 << 5;
        }
        }

        /// ======================================================================
        /// Get Enabled Effects
        ///
        /// Each bit should be considered as a "usable" effect id
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct BacklightGetEnabledEffectsRequest(pub ());

        impl From<()> for BacklightGetEnabledEffectsRequest {
            fn from(req: ()) -> Self {
                Self(req)
            }
        }

        impl XapRequest for BacklightGetEnabledEffectsRequest {
            type Response = BacklightGetEnabledEffectsResponse;

            fn id() -> &'static [u8] {
                &[0x06, 0x02, 0x02]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        #[derive(BinRead, Default, Debug, Clone, Serialize, Type)]
        pub struct BacklightGetEnabledEffectsResponse(pub u8);

        /// ======================================================================
        /// Get Config
        ///
        /// Query the current config.
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct BacklightGetConfigRequest(pub ());

        impl From<()> for BacklightGetConfigRequest {
            fn from(req: ()) -> Self {
                Self(req)
            }
        }

        impl XapRequest for BacklightGetConfigRequest {
            type Response = BacklightConfig;

            fn id() -> &'static [u8] {
                &[0x06, 0x02, 0x03]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        /// ======================================================================
        /// Set Config
        ///
        /// Set the current config.
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct BacklightSetConfigRequest(pub BacklightConfig);

        impl From<BacklightConfig> for BacklightSetConfigRequest {
            fn from(req: BacklightConfig) -> Self {
                Self(req)
            }
        }

        impl XapRequest for BacklightSetConfigRequest {
            type Response = ();

            fn id() -> &'static [u8] {
                &[0x06, 0x02, 0x04]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        /// ======================================================================
        /// Save Config
        ///
        /// Save the current config.
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct BacklightSaveConfigRequest(pub ());

        impl From<()> for BacklightSaveConfigRequest {
            fn from(req: ()) -> Self {
                Self(req)
            }
        }

        impl XapRequest for BacklightSaveConfigRequest {
            type Response = ();

            fn id() -> &'static [u8] {
                &[0x06, 0x02, 0x05]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }
    }

    #[allow(dead_code)]
    #[allow(unused_imports)]
    pub mod rgblight {
        use binrw::{BinRead, BinWrite};
        use bitflags::bitflags;
        use serde::{Deserialize, Serialize};
        use specta::Type;

        use crate::xap::spec::types::*;
        use xap_specs::request::XapRequest;
        use xap_specs::response::UTF8String;

        /// ======================================================================
        ///  capabilities
        ///
        /// rgblight subsystem capabilities query. Each bit should be considered as a "usable" route within this subsystem.
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct RgblightCapabilitiesRequest(pub ());

        impl From<()> for RgblightCapabilitiesRequest {
            fn from(req: ()) -> Self {
                Self(req)
            }
        }

        impl XapRequest for RgblightCapabilitiesRequest {
            type Response = RgblightCapabilitiesFlags;

            fn id() -> &'static [u8] {
                &[0x06, 0x03, 0x01]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        #[derive(
            BinRead, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Clone, Copy, Serialize, Type,
        )]
        pub struct RgblightCapabilitiesFlags(u32);

        bitflags! {
                        impl RgblightCapabilitiesFlags: u32 {

        const Capabilities = 1 << 1;
        const GetEnabledEffects = 1 << 2;
        const GetConfig = 1 << 3;
        const SetConfig = 1 << 4;
        const SaveConfig = 1 << 5;
        }
        }

        /// ======================================================================
        /// Get Enabled Effects
        ///
        /// Each bit should be considered as a "usable" effect id
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct RgblightGetEnabledEffectsRequest(pub ());

        impl From<()> for RgblightGetEnabledEffectsRequest {
            fn from(req: ()) -> Self {
                Self(req)
            }
        }

        impl XapRequest for RgblightGetEnabledEffectsRequest {
            type Response = RgblightGetEnabledEffectsResponse;

            fn id() -> &'static [u8] {
                &[0x06, 0x03, 0x02]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        #[derive(BinRead, Default, Debug, Clone, Serialize, Type)]
        pub struct RgblightGetEnabledEffectsResponse(pub u64);

        /// ======================================================================
        /// Get Config
        ///
        /// Query the current config.
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct RgblightGetConfigRequest(pub ());

        impl From<()> for RgblightGetConfigRequest {
            fn from(req: ()) -> Self {
                Self(req)
            }
        }

        impl XapRequest for RgblightGetConfigRequest {
            type Response = RgbLightConfig;

            fn id() -> &'static [u8] {
                &[0x06, 0x03, 0x03]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        /// ======================================================================
        /// Set Config
        ///
        /// Set the current config.
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct RgblightSetConfigRequest(pub RgbLightConfig);

        impl From<RgbLightConfig> for RgblightSetConfigRequest {
            fn from(req: RgbLightConfig) -> Self {
                Self(req)
            }
        }

        impl XapRequest for RgblightSetConfigRequest {
            type Response = ();

            fn id() -> &'static [u8] {
                &[0x06, 0x03, 0x04]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        /// ======================================================================
        /// Save Config
        ///
        /// Save the current config.
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct RgblightSaveConfigRequest(pub ());

        impl From<()> for RgblightSaveConfigRequest {
            fn from(req: ()) -> Self {
                Self(req)
            }
        }

        impl XapRequest for RgblightSaveConfigRequest {
            type Response = ();

            fn id() -> &'static [u8] {
                &[0x06, 0x03, 0x05]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }
    }

    #[allow(dead_code)]
    #[allow(unused_imports)]
    pub mod rgbmatrix {
        use binrw::{BinRead, BinWrite};
        use bitflags::bitflags;
        use serde::{Deserialize, Serialize};
        use specta::Type;

        use crate::xap::spec::types::*;
        use xap_specs::request::XapRequest;
        use xap_specs::response::UTF8String;

        /// ======================================================================
        ///  capabilities
        ///
        /// rgb matrix subsystem capabilities query. Each bit should be considered as a "usable" route within this subsystem.
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct RgbmatrixCapabilitiesRequest(pub ());

        impl From<()> for RgbmatrixCapabilitiesRequest {
            fn from(req: ()) -> Self {
                Self(req)
            }
        }

        impl XapRequest for RgbmatrixCapabilitiesRequest {
            type Response = RgbmatrixCapabilitiesFlags;

            fn id() -> &'static [u8] {
                &[0x06, 0x04, 0x01]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        #[derive(
            BinRead, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Clone, Copy, Serialize, Type,
        )]
        pub struct RgbmatrixCapabilitiesFlags(u32);

        bitflags! {
                        impl RgbmatrixCapabilitiesFlags: u32 {

        const Capabilities = 1 << 1;
        const GetEnabledEffects = 1 << 2;
        const GetConfig = 1 << 3;
        const SetConfig = 1 << 4;
        const SaveConfig = 1 << 5;
        }
        }

        /// ======================================================================
        /// Get Enabled Effects
        ///
        /// Each bit should be considered as a "usable" effect id
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct RgbmatrixGetEnabledEffectsRequest(pub ());

        impl From<()> for RgbmatrixGetEnabledEffectsRequest {
            fn from(req: ()) -> Self {
                Self(req)
            }
        }

        impl XapRequest for RgbmatrixGetEnabledEffectsRequest {
            type Response = RgbmatrixGetEnabledEffectsResponse;

            fn id() -> &'static [u8] {
                &[0x06, 0x04, 0x02]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        #[derive(BinRead, Default, Debug, Clone, Serialize, Type)]
        pub struct RgbmatrixGetEnabledEffectsResponse(pub u64);

        /// ======================================================================
        /// Get Config
        ///
        /// Query the current config.
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct RgbmatrixGetConfigRequest(pub ());

        impl From<()> for RgbmatrixGetConfigRequest {
            fn from(req: ()) -> Self {
                Self(req)
            }
        }

        impl XapRequest for RgbmatrixGetConfigRequest {
            type Response = RgbMatrixConfig;

            fn id() -> &'static [u8] {
                &[0x06, 0x04, 0x03]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        /// ======================================================================
        /// Set Config
        ///
        /// Set the current config.
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct RgbmatrixSetConfigRequest(pub RgbMatrixConfig);

        impl From<RgbMatrixConfig> for RgbmatrixSetConfigRequest {
            fn from(req: RgbMatrixConfig) -> Self {
                Self(req)
            }
        }

        impl XapRequest for RgbmatrixSetConfigRequest {
            type Response = ();

            fn id() -> &'static [u8] {
                &[0x06, 0x04, 0x04]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }

        /// ======================================================================
        /// Save Config
        ///
        /// Save the current config.
        /// ======================================================================
        #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
        pub struct RgbmatrixSaveConfigRequest(pub ());

        impl From<()> for RgbmatrixSaveConfigRequest {
            fn from(req: ()) -> Self {
                Self(req)
            }
        }

        impl XapRequest for RgbmatrixSaveConfigRequest {
            type Response = ();

            fn id() -> &'static [u8] {
                &[0x06, 0x04, 0x05]
            }

            fn xap_version() -> u32 {
                0x00000300
            }
        }
    }
}

#[allow(dead_code)]
#[allow(unused_imports)]
pub mod audio {
    use binrw::{BinRead, BinWrite};
    use bitflags::bitflags;
    use serde::{Deserialize, Serialize};
    use specta::Type;

    use crate::xap::spec::types::*;
    use xap_specs::request::XapRequest;
    use xap_specs::response::UTF8String;

    /// ======================================================================
    ///  capabilities
    ///
    /// Audio subsystem capabilities query. Each bit should be considered as a "usable" route within this subsystem.
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct AudioCapabilitiesRequest(pub ());

    impl From<()> for AudioCapabilitiesRequest {
        fn from(req: ()) -> Self {
            Self(req)
        }
    }

    impl XapRequest for AudioCapabilitiesRequest {
        type Response = AudioCapabilitiesFlags;

        fn id() -> &'static [u8] {
            &[0x07, 0x01]
        }

        fn xap_version() -> u32 {
            0x00000300
        }
    }

    #[derive(
        BinRead, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Clone, Copy, Serialize, Type,
    )]
    pub struct AudioCapabilitiesFlags(u32);

    bitflags! {
                    impl AudioCapabilitiesFlags: u32 {

    const Capabilities = 1 << 1;
    const GetConfig = 1 << 3;
    const SetConfig = 1 << 4;
    const SaveConfig = 1 << 5;
    }
    }

    /// ======================================================================
    /// Get Config
    ///
    /// Query the current config.
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct AudioGetConfigRequest(pub ());

    impl From<()> for AudioGetConfigRequest {
        fn from(req: ()) -> Self {
            Self(req)
        }
    }

    impl XapRequest for AudioGetConfigRequest {
        type Response = AudioConfig;

        fn id() -> &'static [u8] {
            &[0x07, 0x03]
        }

        fn xap_version() -> u32 {
            0x00000300
        }
    }

    /// ======================================================================
    /// Set Config
    ///
    /// Set the current config.
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct AudioSetConfigRequest(pub AudioConfig);

    impl From<AudioConfig> for AudioSetConfigRequest {
        fn from(req: AudioConfig) -> Self {
            Self(req)
        }
    }

    impl XapRequest for AudioSetConfigRequest {
        type Response = ();

        fn id() -> &'static [u8] {
            &[0x07, 0x04]
        }

        fn xap_version() -> u32 {
            0x00000300
        }
    }

    /// ======================================================================
    /// Save Config
    ///
    /// Save the current config.
    /// ======================================================================
    #[derive(BinWrite, Default, Debug, Clone, Serialize, Type)]
    pub struct AudioSaveConfigRequest(pub ());

    impl From<()> for AudioSaveConfigRequest {
        fn from(req: ()) -> Self {
            Self(req)
        }
    }

    impl XapRequest for AudioSaveConfigRequest {
        type Response = ();

        fn id() -> &'static [u8] {
            &[0x07, 0x05]
        }

        fn xap_version() -> u32 {
            0x00000300
        }
    }
}

pub mod types {
    use binrw::{BinRead, BinWrite};
    use serde::{Deserialize, Serialize};
    use specta::Type;

    /// Packet format for broadcast messages.
    #[derive(BinRead, BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
    pub struct BroadcastHeader {
        pub r#type: u8,
        pub length: u8,
    }

    /// Config for lighting subsystem
    #[derive(BinRead, BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
    pub struct BacklightConfig {
        pub enable: u8,
        pub mode: u8,
        pub val: u8,
    }

    /// Packet format for inbound data.
    #[derive(BinRead, BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
    pub struct RequestHeader {
        pub length: u8,
    }

    /// Packet format for outbound data.
    #[derive(BinRead, BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
    pub struct ResponseHeader {
        pub length: u8,
    }

    /// RGB config for RGB lighting subsystem
    #[derive(BinRead, BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
    pub struct RgbLightConfig {
        pub enable: u8,
        pub mode: u8,
        pub hue: u8,
        pub sat: u8,
        pub val: u8,
        pub speed: u8,
    }

    /// RGB config for RGB matrix subsystem
    #[derive(BinRead, BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
    pub struct RgbMatrixConfig {
        pub enable: u8,
        pub mode: u8,
        pub hue: u8,
        pub sat: u8,
        pub val: u8,
        pub speed: u8,
        pub flags: u8,
    }

    /// Config for audio subsystem
    #[derive(BinRead, BinWrite, Default, Debug, Clone, Serialize, Deserialize, Type)]
    pub struct AudioConfig {
        pub enable: u8,
        pub clicky_enable: u8,
    }
}
